# version: '2.28.1' #to be changed
name: inception

services:
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
      - "8080:80"
    networks:
      - net_inception
    # depends_on:
    #   wordpress:
    #     condition: service_healthy
    env_file:
      - path: ./nginx.env
        required: true

    # secrets:
    #   - server-certificate
    restart: on-failure:3
    volumes:
      - db-data:/var/lib/data #to be changed


  wordpress:
    build: :./requirements/wordpress
    ports:
      -

networks:
  net_inception:
    driver: bridge

# secrets:
#   server-certificate:
#     file: ./server.cert

volumes:
  db-data:
