# version: '3.8'
name: inception
services:
  wordpress:
    container_name: wordpress
    secrets:
      - wp-secrets
      - db-secrets
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    networks:
      - net_inception
    restart: on-failure:3
    volumes:
      - wp-volume:/var/www/localhost/htdocs/wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    depends_on:
      - wordpress
    restart: on-failure:3
    volumes:
      - wp-volume:/var/www/localhost/htdocs/wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    networks:
      - net_inception
    restart: on-failure:3
    volumes:
      - db-volume:/var/lib/mysql
    secrets:
      - db-secrets
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    networks:
      - net_inception
    restart: on-failure:3
    depends_on:
      - wordpress
  vsftpd:
    container_name: ftp
    build:
      context: ./requirements/bonus/vsftpd
      dockerfile: Dockerfile
      args:
        FTP_USR: ${FTP_USR}
    networks:
      - net_inception
    restart: on-failure:3
    volumes:
      - wp-volume:/var/www/localhost/htdocs/wordpress
    ports:
      - "21:21"
      - "10000-10002:10000-10002"
    secrets:
      - ftp-secrets
  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    networks:
      - net_inception
    restart: on-failure:3
    depends_on:
      - mariadb
  restic:
    container_name: restic
    build:
      context: ./requirements/bonus/restic
      dockerfile: Dockerfile
    restart: on-failure:3
    volumes:
      - wp-volume:/var/data/wordpress
      - db-volume:/var/data/mariadb
      - bu-volume:/srv/restic-repo
    secrets:
      - sr-secrets
    depends_on:
      - wordpress
  static_page:
    container_name: showcase
    build:
      context: ./requirements/bonus/static_page
      dockerfile: Dockerfile
    restart: on-failure:3
    networks:
      - net_inception
  notifier:
    container_name: notifier
    build:
      context: ./requirements/bonus/notifier
      dockerfile: Dockerfile
    restart: on-failure:3
    networks:
      - net_inception
    secrets:
      - not-secrets
    depends_on:
      - nginx
      - wordpress
networks:
  net_inception:
    driver: bridge
volumes:
  wp-volume:
    name: wp-volume
    driver_opts:
      o: bind
      type: none
      device: /Users/HP/data/wordpress
  db-volume:
    name: db-volume
    driver_opts:
      o: bind
      type: none
      device: /Users/HP/data/mariadb
  bu-volume:
    name: backup
    driver_opts:
      o: bind
      type: none
      device: /Users/HP/data/backup
secrets:
  db-secrets:
    file: ../secrets/db_secrets.txt
  wp-secrets:
    file: ../secrets/wp_secrets.txt
  sr-secrets:
    file: ../secrets/restic_pwd.txt
  ftp-secrets:
    file: ../secrets/ftp_secrets.txt
  not-secrets:
    file: ../secrets/notif_secrets.txt
