# version: '3.8'
name: inception
services:
  wordpress:
    container_name: wordpress
    secrets:
      - wp-secrets
      - db-secrets
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_HOST: ${DB_HOST}
        DB_USER: ${DB_USER}
        DB_USRPWD: ${DB_USRPWD}
        DB_RTPWD: ${DB_RTPWD}
        WP_AUTHKEY: ${WP_AUTHKEY}
        WP_SECURE_AUTH_KEY: ${WP_SECURE_AUTH_KEY}
        WP_LOGGED_IN_KEY: ${WP_LOGGED_IN_KEY}
        WP_NONCE_KEY: ${WP_NONCE_KEY}
        WP_AUTH_SALT: ${WP_AUTH_SALT}
        WP_SECURE_AUTH_SALT: ${WP_SECURE_AUTH_SALT}
        WP_LOGGED_IN_SALT: ${WP_LOGGED_IN_SALT}
        WP_NONCE_SALT: ${WP_NONCE_SALT}
    depends_on:
      - mariadb
    networks:
      - net_inception
    restart: on-failure:3
    volumes:
      - wp-volume:/var/www/localhost/htdocs/wordpress
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    depends_on:
      - wordpress
    restart: on-failure:3
    volumes:
      - wp-volume:/var/www/localhost/htdocs/wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_USRPWD: ${DB_USRPWD}
        DB_RTPWD: ${DB_RTPWD}
    networks:
      - net_inception
    restart: on-failure:3
    volumes:
      - db-volume:/var/lib/mysql
    secrets:
      - db-secrets
networks:
  net_inception:
    driver: bridge
volumes:
  wp-volume:
    name: wp-volume
    driver_opts:
      o: bind
      type: none
      device: /Users/${USER}/data/wordpress
  db-volume:
    name: db-volume
    driver_opts:
      o: bind
      type: none
      device: /Users/${USER}/data/mariadb
secrets:
  db-secrets:
    file: ./secrets/db_secrets.txt
  wp-secrets:
    file: ./secrets/wp_secrets.txt
