version: '2.28.1'

name: inception

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - net_inception
    # secrets:
    #   - server-certificate
    restart: on-failure:3
    volumes:
      - wordpress_data:/var/www/localhost/htdocs/wordpress #to be changed


  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: true
    depends_on:
      - mariadb
    networks:
      - net_inception
    restart: on-failure:3
    volumes:
      - wordpress_data:/var/www/localhost/htdocs/wordpress
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_ADMN: ${DB_ADMN}
        DB_USER: ${DB_USER}
        DB_USRPWD: ${DB_USRPWD}
        DB_ADMNPWD: ${DB_ADMNPWD}
        DB_RTPWD: ${DB_RTPWD}
    networks:
      - net_inception
    restart: on-failure:3
    secrets:
      - mariadb-secrets
    volumes:
      - db-data:/var/lib/mysql

networks:
  net_inception:
    driver: bridge

secrets:
  mariadb-secrets:
    file: ./requirements/mariadb/secrets.txt
#   server-certificate:
#     file: ./server.cert

volumes:
  db-data:
    name: db-data
  wordpress_data:
    name: wp-data
